version: '3.8'
services:
  postgres_db:
    image: postgres:14
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    networks:
      - data_analysis_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  data_analysis_network:
    driver: bridge

volumes:
  postgres_data:
